# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import strawberry.fields.md5


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_hash', strawberry.fields.md5.MD5Field(always_update=True, editable=False, populate_from='description')),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_hash', strawberry.fields.md5.MD5Field(always_update=True, editable=False, populate_from='summary')),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pages', models.PositiveIntegerField(default=200)),
                ('stock_count', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ['isbn'],
            },
        ),
    ]
