# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import strawberry.fields.md5


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='credits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='credits_hash',
            field=strawberry.fields.md5.MD5Field(always_update=True, default=' ', editable=False, populate_from='credits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='description_hash',
            field=strawberry.fields.md5.MD5Field(always_update=True, blank=True, editable=False, null=True, populate_from='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary_hash',
            field=strawberry.fields.md5.MD5Field(always_update=True, blank=True, editable=False, null=True, populate_from='summary'),
        ),
    ]
