# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import strawberry.fields.md5


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180520_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis_hash',
            field=strawberry.fields.md5.MD5Field(always_update=True, default=' ', editable=False, populate_from='synopsis'),
            preserve_default=False,
        ),
    ]
